### ISSUE TITLE
Adapt workspace

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-molekulares-tumorboard#3]
GitHub action auf dev  aufsetzen
dev protecten
simplifier beantragen
ig yaml bearbeiten

**Comment by msusky** [comment]
Bei der YAML Konfiguration kann ich dir gern helfen, wenn das noch etwas Zeit hat. Per Default wird zumindest der Workflow im Onkologie Repo nur auf `main` und `dev` getriggert (siehe https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/blob/922a64c2c58e73a8253bb8fcd0ca7a12b27029dc/.github/workflows/main.yml#L9). D.h. wenn wir unser Branching Modell während der Bearbeitung verfolgen, dürften dahingehend keine Probleme auftreten.

**Comment by ThomasDeBe** [comment]
Danke @msusky für den Hinweis, das ist aber nicht die Action die ich meinte. Das eine ist einereine FHIR-Validation, und das andere ist das automatische Bauen der FHIR-JSON-Ressourcen in der Pipeline. Das müssten wir noch konfiguerieren. 

Du hast recht, es eilt natürlich nicht mega, aber ich gucke es mir gerne an und will immer dazulernen. Falls ich es nicht gebacken bekomme, melde ich mich nochmal. Danke für die Unterstützung!
