### ISSUE TITLE
fehlende DNA Fusion im NGS_Bericht

### ISSUE THREAD

**Issue by milah** [medizininformatik-initiative/kerndatensatzmodul-molekulares-tumorboard#33]
Fehlt im NGS_Bericht nicht noch DNA-Fusion (und Ploidie)? Es ist zwar mit einem Pfeil verlinkt aber nicht aufgeführt. 

Vielleicht verstehe ich auch nicht die Bedeutung der Pfeile. Dann wäre ich für eine Erklärung dankbar. 

https://github.com/medizininformatik-initiative/kerndatensatzmodul-molekulares-tumorboard/blob/e0447b949678deace685eac7ef8b7384ba6be996/information-model/MII_MTB_LM_wo_cardinalities.pu#L102

**Comment by ThomasDeBe** [comment]
Hallo @milah, 

DNA-Fusion und Ploidie fehlt in der Klasse NGS_Bericht, danke für den Hinweis, das korrigieren wir .
Diese sind natürlich trotzdem Bestandteil der Klasse. 

Wir bitten zu beachten, dass wir noch mitten in der Profilierungsphase sind und sich daher auch noch Änderungen an Profilen oder dem Informationsmodell geben kann. Gerne sind Sie zur Kommentierungsphase eingeladen, die wir vsl. im Q1 2025 abhalten werden.

**Comment by ThomasDeBe** [comment]
@Wormfriend im PlantUML ändern und bild als svg exportieren
